# Generated by Django 4.2.7 on 2026-01-07 18:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('ngo', 'NGO'), ('shelter', 'Shelter'), ('individual', 'Individual'), ('community', 'Community Center')], max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity', models.IntegerField(help_text='Number of people can serve', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_occupancy', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipient_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipientNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.CharField(max_length=100)),
                ('quantity_needed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='recipients.recipientprofile')),
            ],
            options={
                'db_table': 'recipient_needs',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipientprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='recipient_p_latitud_9b03d9_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientprofile',
            index=models.Index(fields=['recipient_type'], name='recipient_p_recipie_9fcefb_idx'),
        ),
    ]
