# Generated by Django 4.2.7 on 2026-01-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Auto-generated from coordinates via reverse geocoding', max_length=255, null=True),
        ),
    ]
