# Generated by Django 6.0.1 on 2026-01-10 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_recipientprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientprofile',
            name='capacity',
            field=models.IntegerField(help_text='Maximum number of people can serve', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='current_occupancy',
            field=models.IntegerField(default=0, help_text='Current number of people being served'),
        ),
    ]
