# Generated by Django 4.2.7 on 2026-01-07 18:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('donor_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('grocery', 'Grocery Store'), ('bakery', 'Bakery'), ('catering', 'Catering Service'), ('hotel', 'Hotel'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_donations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donor_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='donors.donorprofile')),
            ],
            options={
                'db_table': 'donor_schedules',
                'ordering': ['day_of_week'],
                'unique_together': {('donor', 'day_of_week')},
            },
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='donor_profi_latitud_4652e3_idx'),
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['is_verified'], name='donor_profi_is_veri_0ddfb2_idx'),
        ),
    ]
