# Generated by Django 4.2.7 on 2026-01-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
