# Generated by Django 4.2.7 on 2026-01-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donorprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='donor_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('grocery', 'Grocery Store'), ('bakery', 'Bakery'), ('catering', 'Catering Service'), ('hotel', 'Hotel'), ('retail', 'Retail Store'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Auto-generated from coordinates via reverse geocoding', max_length=255, null=True),
        ),
    ]
