# Generated by Django 4.2.7 on 2026-01-07 18:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0001_initial'),
        ('donors', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_pickup_time', models.DateTimeField()),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_delivery_time', models.DateTimeField()),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_meals', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donorprofile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_donations', to='recipients.recipientprofile')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='volunteers.volunteerprofile')),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('average_shelf_life_hours', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
                'db_table': 'food_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_waste_prevented_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2_emissions_saved_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meals_provided', models.IntegerField()),
                ('people_fed', models.IntegerField()),
                ('tax_deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='inventory.donation')),
            ],
            options={
                'verbose_name_plural': 'Impact Metrics',
                'db_table': 'impact_metrics',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('expiry_date', models.DateTimeField()),
                ('pickup_before', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.foodcategory')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='donors.donorprofile')),
            ],
            options={
                'db_table': 'food_items',
                'ordering': ['urgency_level', 'expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.donation')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_items', to='inventory.fooditem')),
            ],
            options={
                'db_table': 'donation_items',
            },
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['donor', 'is_available'], name='food_items_donor_i_d85ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['expiry_date', 'is_available'], name='food_items_expiry__22d4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['urgency_level'], name='food_items_urgency_b03b00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='donationitem',
            unique_together={('donation', 'food_item')},
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'status'], name='donations_donor_i_9c0085_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['recipient', 'status'], name='donations_recipie_f4cf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['volunteer', 'status'], name='donations_volunte_bd0e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['scheduled_pickup_time'], name='donations_schedul_d1af8e_idx'),
        ),
    ]
